spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
      url:
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: info


